# Generated by Django 3.2.11 on 2022-02-04 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('st_code', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_register.intake')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_register.track')),
            ],
        ),
    ]
